version: '3'

services:
  # Connect to database
  # pgcli postgresql://postgres@localhost:5434/waia
  waia-spark-sql-db:
    image: postgres:14.1-alpine
    restart: always
    networks:
      - waia
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=waia
    ports:
      - '5434:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  spark-sql:
    build: ./
    depends_on:
      - waia-spark-sql-db
    networks:
      - waia
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app

volumes:
  db:
    driver: local

networks:
  waia:
    name: waia_containers
