version: "2"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: waia_kafka_broker
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  kafka_data:
    driver: local
